server:
  port: 3120

spring:
  application:
    name: gateway

  cloud:
    consul:
      host: ${CONSUL-HOST:127.0.0.1}
      port: ${CONSUL-PORT:8500}
      discovery:
        prefer-agent-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: NEVER