server:
  port: 3400

spring:
  application:
    name: payment
  cloud:
    consul:
      host: ${consul-host:127.0.0.1}
      port: ${consul-port:8500}
      discovery:
        prefer-agent-address: true
